apiVersion: v1
kind: Secret
metadata:
  name: vaultcore-secrets
  labels:
    app.kubernetes.io/name: vaultcore
    app.kubernetes.io/part-of: vaultcore-platform
type: Opaque
stringData:
  POSTGRES_USER: 'vaultadmin'
  POSTGRES_PASSWORD: 'vaultsecretpassword2026'
  RABBITMQ_DEFAULT_USER: 'vaultadmin'
  RABBITMQ_DEFAULT_PASS: 'vaultsecretpassword2026'
  JWT_SECRET: 'k8s-prod-vaultcore-jwt-secret-key-2026-super-secure'
  REFRESH_TOKEN_SECRET: 'k8s-prod-vaultcore-refresh-secret-key-2026-super-secure'
  INTERNAL_API_KEY: 'vaultcore-internal-secure-api-key-2026'
